### ISSUE TITLE
Rest API Design and Implementation (Backend)

### ISSUE THREAD

**Issue by ishan710** [net-art-uchicago/cta-file-sharing#11]
I will be working on designing the backend rest APIs for our application. The primary type of services that rest APIs perform is reading and writing data from the database such as 
1. Posting data of user location to the database
2. Posting the files that users share onto the database
3. Linking different buttons on the front move between different pages (unsure if this still counts as rest API)

I will be working closely with the backend database team to ensure data is read and written in the correct formats. I will also have to be in touch with someone from the frontend team to decide what all rest api's would be needed (probably Isaac can help out). I would write most of the code in JS and Python.

**Comment by shayna-k** [comment]
- endpoint per functionality
- create urls based on endpoints to get that data from you 
- [use async/await fetch]

**Comment by shayna-k** [comment]
Requests framework [WIP]:

POST:
- poem with location

GET:
- poems for that location
- each page

Who is going to handle getting map data?
