### ISSUE TITLE
First Page

### ISSUE THREAD

**Issue by azarias22** [net-art-uchicago/cta-file-sharing#12]
I will be working on the first page where users can wait -> create. This will be a website page designed for a mobile phone. It will have an introduction followed by a couple of text bubbles. At the bottom of the page, it will include a text input field where users can type and post comments. The graphic design for this page is shown below:
 
<img width="225" alt="Screen Shot 2022-11-08 at 1 25 33 PM" src="https://user-images.githubusercontent.com/103261517/200656798-b2a109d3-5386-44c1-9573-d4b01f29332d.png">

**Comment by nbriz** [comment]
this looks/sounds great to me, one thing to make sure of is that any CSS u make for the text bubbles are also shared by anyone else creating any other pages that use text bubbles
