### ISSUE TITLE
Roles / Tasks

### ISSUE THREAD

**Issue by nbriz** [net-art-uchicago/cta-file-sharing#2]
This project is definitely going to involve both "[frontend](https://github.com/net-art-uchicago/cta-file-sharing/tree/main/frontend)" and "[backend](https://github.com/net-art-uchicago/cta-file-sharing/tree/main/backend)" work. The backend will be pure JavaScript while the fronted will involve a combination of HTML, CSS and JavaScript. Think about what part of the project you're most intersted in working on and leave a comment below (otherwise I'll assign you to a specific area and set of tasks in class next week)

Some of the backend tasks might include:
  - creating our own REST API endpoints that the frontend will use to POST user data to as well as GET user data from.
  - creating some sort of database to store our user data, this might be as simple as working with the file system (storing files in foldres, creating/editing text files, like csv/json/etc) or could involve integrating a database system like MySQL, MongoDB, etc.
  - sending requests to 3rd party REST APIs, like the city of Chicago's [Train Tracker API](https://www.transitchicago.com/developers/ttdocs/) for example.

Some of the frontend tasks might include:
  - creating interactive maps, using frontend JavaScript libraries like [leaflet](https://leafletjs.com/) or [mapbox](https://www.mapbox.com/) (related to this, check out this [CTA train json data](https://github.com/aepton/chicago-maps/blob/master/json/cta_rail.topojson) I found, might be useful)
  - maps require "image tiles", there are some [open source map tiles](https://openmaptiles.org/) but we might also want to make our own (check out this [vintage CTA map](https://archive.org/details/CTATrainMap1/CTA%20Train%20Map2.jpg) I found, could be good inspo) 
  - creating the rest of the app's "views" and UI, this will invovle HTML and CSS
  - writing the frontend logic for any of the UI (ex: submitting user data to our servers REST API), this will require frontend JavaScript

**Comment by ashantiowusu-brafi** [comment]
I am interested in backend. I have experience with MySQL and am eager to learn how to implement a database into a web app successfully. I think the relationship between the API and the web app is an important aspect of security that I am hoping to gather more thoughts on. I was using Heroku to host a web application. Integrating ClearDB cloud hosting to build a database for a project. I got stuck on how to create a _submission form_ that stored users' files in this cloud-hosted Database. The issue was with the various file types and trying to write code for specific sizes and limit users on the number of times they could upload things/photos/audio/video. Simultaneously I was coding the front-end submission form and frankly was overworked and frustrated with the decisions I needed to make on the visual side. Hoping to work that out here :D

**Comment by nbriz** [comment]
great @ashantiowusu-brafi! we'll definitely need to store data, but exactly *how* we do it will depend on the details. once we've further defined the concept we'll be able to define the technical tasks in more detail. as far as the "database" is concerned, we may need to implement a conventional database (like MySQL or MonoDB), but we might also be able to get away w/something a little more DIY/minimal (like working directly w/the file system && saving text files, `.json`, `.csv`, etc), or we might decide something in the middle like SQLite is more appropriate.

As for deploying our app, that's another decision we'll need to make when we near the end of the quarter, Heroku might work out great for us, that said, sometimes services like that abstract the process in a way that's practical in practice, but obscures our understanding of the systems. given our learning goals, we may take another approach that helps us better understand the open + decentralized nature of the platform we're developing for (the World Wide Web) and the infrastructure it operates on  (the Internet).

**Comment by akhaiat2** [comment]
I would say that I have more skills that pertain to frontend work (from previous experience) but I would love to focus on backend dev to build new skills. In terms of backend work, I especially want to be working on the requests from 3rd party rest APIs (such as CTA bus API) as well as the database aspect (I have used Firebase in the past, but open to anything really). I can also help others with frontend work if needed!

**Comment by ajchu28** [comment]
I'd be interested in working on the frontend side of things! I recently did a project which involved working with Mapbox GL JS.

**Comment by andrewscottcohen** [comment]
I have more experience on frontend and would be happy to help there - but I would also really love to learn more about API requests and building out the database!

**Comment by aureliejr** [comment]
I have more experience with front end, but not a huge amount, and I'd like to learn more about backend programming, so I'd be happy with either

**Comment by cal-ledoux** [comment]
I am happy to work with either, but I am particularly interested in frontend logic and map design if that role is still available! If not, I am super curious about all aspects!

**Comment by azarias22** [comment]
Even though I have worked with frontend more than backend, I will be happy to work on either.  For frontend I can work on writing the frontend logic for any of the UIs. And for backend, I can work on creating REST API endpoints to POST and GET data.

**Comment by bermanisaac** [comment]
Just some musings on more granular tasks that we'll need to include in the project (not sorted particularly well):

file submit page/text writing page (frontend, text writing "app")
file adding protocol (HTTP POST request?)
file repository (potentially just a JSON file and manipulate it in memory?)
bus GPS location -- chicago API access
user GPS location -- browser API access
files live on buses?
data structure to track movement of the files
function to determine "location" of files based on which bus route they're on and where the bus is

identify which bus a person is on (frontend page)
identify which bus a person is on (backend function)
check if user is even on a bus route? can the user use the app at all if they're off-route?

wait -> create
detect if user is moving or not (browser GPS/gyro/accelerometer? access)

move -> consume
detect if user is moving (browser GPS...)
feed them a file (frontend file viewing)
feed them a file (backend decide which file to provide)

synchronous data? detecting how many current active users of the app (backend)
active current users on a certain bus / on a certain route (backend)
affect the frontend based on current activity / realtime data (frontend)

**Comment by bermanisaac** [comment]
Server/Client Communication Diagram:

REST API for asynchronous communcation:
Server sends:
- Initial page

Client sends:
- Desired bus route
- Current location (to know stop/which bus they're on)
- Poem

*start moving*
Client sends:
- Location

Server sends:
- Poem to read

Question: Does any of the bus tracking logic lie on the frontend? Or does the backend need to constantly communicate about bus location vs user location to keep tracking accurate

Realtime data communication would happen over a dedicated socket

**Comment by nbriz** [comment]
Front-End
  - graphic design for views
  - code for views (html/css)
    - desktop page (redirect)
    - wait -> create (initial chat)
    - move -> consume (viewing other texts; we decide)
    - passenger poets select for other texts
      - map interface
      - other interfaces

  - code for views (JavaScript)
    - POST: passenger poet's bus route + text (Fetch API)
    - POST: location information (Fetch API)
    - update "wait -> create" chat view (DOM API)
    - GET: texts (Fetch API)
    - update "move -> consume" chat view (DOM API)
    - map interaction 
    - other interface interaction

Back-End
  REST API
  - POST: passenger poet's bus route + text 
  - POST: location information 
  - GET: texts
  DataBase
  - ????
