### ISSUE TITLE
Desktop Page

### ISSUE THREAD

**Issue by shmoopyyy** [net-art-uchicago/cta-file-sharing#8]
I will be creating our desktop page so that people can be properly redirected to their mobile website. I still want our desktop to keep our theme/look intact, so I hope to incorporate those necessary colors/images. I also want to implement a QR code like we talked about, so that people don't have to re-enter the link. This should take mostly HTML/CSS work, with maybe a little Javascript.

**Comment by nbriz** [comment]
@shmoopyyy great! do u have a design for this yet? once u do share an image of it here && i can comment on it + approve it before u start writing code
